/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114855-g35ae44c615-20240418"
#endif /* AVUTIL_FFVERSION_H */
